/*==============================================================
 CHOCOLATE SALES ANALYSIS
 BASIC BUSINESS QUESTIONS
==============================================================*/

/*==============================================================
1. SALES OVERVIEW
==============================================================*/


/*--------------------------------------------------------------
1.1 What is the total revenue generated?
--------------------------------------------------------------*/

SELECT
SUM(amount_numeric) AS total_revenue
FROM chocolate_sales;


/*--------------------------------------------------------------
1.2 How many boxes have been shipped?
--------------------------------------------------------------*/

SELECT
SUM(boxes_shipped) AS total_boxes
FROM chocolate_sales;


/*--------------------------------------------------------------
1.3 What is the average order value?
--------------------------------------------------------------*/

SELECT
ROUND(AVG(amount_numeric),2) AS average_order_value
FROM chocolate_sales;


/*==============================================================
2. PRODUCT ANALYSIS
==============================================================*/


/*--------------------------------------------------------------
2.1 Which products generate the highest revenue?
--------------------------------------------------------------*/

SELECT
product,
SUM(amount_numeric) AS revenue
FROM chocolate_sales
GROUP BY product
ORDER BY revenue DESC
LIMIT 10;


/*--------------------------------------------------------------
2.2 Which products generate the highest revenue per box shipped?
--------------------------------------------------------------*/

SELECT
product,
ROUND(
SUM(amount_numeric)/SUM(boxes_shipped),2) AS revenue_per_box
FROM chocolate_sales
GROUP BY product
ORDER BY revenue_per_box DESC;



/*==============================================================
3. COUNTRY ANALYSIS
==============================================================*/


/*--------------------------------------------------------------
3.1 Revenue generated by each country
--------------------------------------------------------------*/

SELECT
country,
SUM(amount_numeric) AS revenue
FROM chocolate_sales
GROUP BY country
ORDER BY revenue DESC;


/*--------------------------------------------------------------
3.2 Average order value by country
--------------------------------------------------------------*/

SELECT
country,
ROUND(AVG(amount_numeric),2) AS average_order_value
FROM chocolate_sales
GROUP BY country
ORDER BY average_order_value DESC;



/*==============================================================
4. SALESPERSON ANALYSIS
==============================================================*/


/*--------------------------------------------------------------
4.1 Which salespeople generate the most revenue?
--------------------------------------------------------------*/

SELECT
sales_person,
SUM(amount_numeric) AS revenue
FROM chocolate_sales
GROUP BY sales_person
ORDER BY revenue DESC;


/*--------------------------------------------------------------
4.2 Sales consistency by salesperson
--------------------------------------------------------------*/

SELECT
sales_person,
COUNT(*) AS total_orders,
ROUND(AVG(amount_numeric),2) AS average_order,
MIN(amount_numeric) AS smallest_sale,
MAX(amount_numeric) AS largest_sale
FROM chocolate_sales
GROUP BY sales_person
ORDER BY average_order DESC;



/*==============================================================
5. TIME ANALYSIS
==============================================================*/


/*--------------------------------------------------------------
5.1 Monthly revenue trend
--------------------------------------------------------------*/

SELECT
EXTRACT(YEAR FROM sale_date_actual) AS year,
EXTRACT(MONTH FROM sale_date_actual) AS month,
SUM(amount_numeric) AS revenue
FROM chocolate_sales
GROUP BY
EXTRACT(YEAR FROM sale_date_actual),
EXTRACT(MONTH FROM sale_date_actual)
ORDER BY year, month;